FROM golang:1.23

RUN apt-get update && apt-get install git -y

WORKDIR /opt
RUN git clone https://github.com/czcorpus/apiguard

WORKDIR /opt/apiguard
RUN make build && mkdir /var/lib/apiguard/statusData -p

COPY ./install/docker/apiguard.json ./conf.json

CMD ["./apiguard", "start", "conf.docker.json"]